name: vpml
channels:
  - https://conda.ccdc.cam.ac.uk
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - comm=0.2.2
  - debugpy=1.8.2
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy=2.0.1
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.2
  - python-dateutil=2.9.0
  - python_abi=3.12
  - pyzmq=26.0.3
  - readline=8.2
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.2
  - stack_data=0.6.2
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - pip:
      - ase==3.23.0
      - beautifulsoup4==4.12.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - easyprocess==1.1
      - entrypoint2==1.1
      - et-xmlfile==1.1.0
      - fonttools==4.53.1
      - ipympl==0.9.4
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - networkx==3.3
      - openpyxl==3.1.5
      - pandas==2.2.2
      - patool==2.3.0
      - pillow==10.4.0
      - py3dmol==2.4.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyunpack==0.3
      - rarfile==4.2
      - rdkit==2024.3.5
      - seaborn==0.13.2
      - soupsieve==2.6
      - sympy==1.13.1
      - tabulate==0.9.0
      - tzdata==2024.1
      - widgetsnbextension==4.0.13
